=== PennBBL/core/raml/schemas/definitions/group-output.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "roles": {
      "type": "array",
      "items": {"$ref": "permission.json"},
      "uniqueItems": true
    },
    "created": {
      "type": "string"
    },
    "modified": {
      "type": "string"
    },
    "_id": {
      "type": "string"
    }
  },
  "required": [
    "roles",
    "created",
    "modified",
    "_id"
  ]
}

=== PennBBL/core/raml/examples/output/group.json
{
  "name": "Test Group",
  "roles": [
    {
      "access": "admin",
      "_id": "group_admin@fakeuser.com",
      "site": "local"
    },
    {
      "access": "rw",
      "_id": "group_member_read-write@fakeuser.com",
      "site": "local"
    },
    {
      "access": "ro",
      "_id": "group_member_read-only@fakeuser.com",
      "site": "local"
    }
  ],
  "created": "2016-08-19T11:41:15.360000+00:00",
  "modified": "2016-08-19T11:41:15.360000+00:00",
  "_id": "test_group"
}
